# Generated by Django 3.2.4 on 2021-08-23 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('chemical_name', models.CharField(max_length=100)),
                ('date_time_entered', models.DateTimeField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_balance', models.IntegerField()),
                ('date_time_of_movement', models.DateTimeField(default=django.utils.timezone.now)),
                ('case_involved_description', models.CharField(max_length=100)),
                ('product_moving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('store_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stores')),
                ('user_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_card_user_involved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stores')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_invoiced_amount', models.FloatField()),
                ('date_time_entry', models.DateTimeField()),
                ('approval', models.BooleanField(default=False)),
                ('products', models.JSONField(null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_order_approver', to=settings.AUTH_USER_MODEL)),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stores')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.suppliers')),
                ('user_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_order_user_involved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
