# Generated by Django 3.2.4 on 2021-08-25 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_time_entered',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 7, 11, 33, 261762, tzinfo=utc)),
        ),
    ]
