# Generated by Django 3.2.4 on 2021-08-26 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_products_date_time_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products', unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_time_entered',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 15, 17, 10, 692253, tzinfo=utc)),
        ),
    ]
