# Generated by Django 3.2.4 on 2021-09-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_externalorder_inventory_inventorycard_products_receivingtemplate_stores_suppliers'),
        ('inventory', '0005_auto_20210827_0933'),
    ]

    operations = [
    ]
